---
# Collection Service Deployment (local version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service
  namespace: ladon-local
  labels:
    app: collection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
  template:
    metadata:
      labels:
        app: collection-service
    spec:
      # Wait for dependencies
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."
              until nc -z postgres.ladon-local.svc.cluster.local 5432; do
                echo "PostgreSQL not ready, waiting..."
                sleep 2
              done
              echo "PostgreSQL is ready!"

      containers:
        - name: collection-service
          # Use local image or build from Dockerfile
          image: collection-service:local
          imagePullPolicy: IfNotPresent  # Use local image
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 9090

          # Environment from ConfigMap
          envFrom:
            - configMapRef:
                name: collection-config

          # Environment from Secrets
          env:
            - name: ALIENVAULT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: collection-secrets
                  key: ALIENVAULT_API_KEY
            - name: ABUSECH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: collection-secrets
                  key: ABUSECH_API_KEY
                  optional: true
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: collection-secrets
                  key: POSTGRES_PASSWORD

          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5

          # Resources (minimal for laptop)
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

---
# Service to expose Collection Service
apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: ladon-local
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    app: collection-service
